export const GET_AIRLINE_DESTINATION_START = 'GET_AIRLINE_DESTINATION_START';
export const GET_AIRLINE_DESTINATION_COMPLETE = 'GET_AIRLINE_DESTINATION_COMPLETE';
export const GET_AIRLINE_DESTINATION_ERROR = 'GET_AIRLINE_DESTINATION_ERROR';
